language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew update
        - brew install --build-from-source openjdk
        - brew tap caskroom/cask
        - brew cask install powershell
    - os: windows
  fast_finish: true


before_script:
  - bash <(wget -O - https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh)
  - pwsh ./macos/install.ps1

script:
  - pwsh ./macos/build.ps1
  - pwsh ./macos/pack.ps1
  - pwsh ./macos/copy-artifacts.ps1
  - pwsh ./linux/build.ps1
  - pwsh ./linux/pack.ps1
  - pwsh ./linux/copy-artifacts.ps1
  - pwsh ./windows/build.ps1
  - pwsh ./windows/pack.ps1
  - pwsh ./windows/copy-artifacts.ps1

script:
  - pwsh ./common/nuget-pack.ps1 -Version "1.7.0.$TRAVIS_BUILD_NUMBER" -NuGet nuget

deploy:
provider: releases
api_key: $GHTOKEN
skip_cleanup: true
file:
  - tdlib.osx.zip
  - tdlib.linux.zip
  - tdlib.window.zip
  - tdlib.native.1.7.0.nupkg
on:
  tags: true